# frontend-staging.yml
# Kelix Frontend — Staging CI/CD (PR validation + staging deploy)
#
# Behavior:
# - PR to staging: Build + Test + Security
# - Push to staging: Build + Test + Security + Deploy to Staging

trigger:
  branches:
    include:
      - staging

pr: none

pool:
  vmImage: ubuntu-24.04

variables:
  NODE_VERSION: '24.x'
  PNPM_VERSION: '10.15.1'
  TRIVY_VERSION: '0.68.2'
  SEMGREP_VERSION: '1.148.0'
  GITLEAKS_VERSION: '8.30.0'
  CDXGEN_VERSION: '12.0.0'
  PYTHON_VERSION: '3.12'
  FRONTEND_APP_LOCATION: 'app'
  PNPM_STORE_PATH: $(Pipeline.Workspace)/.pnpm-store
  TRIVY_CACHE_DIR: $(Pipeline.Workspace)/.trivy
  CACHE_RESTORED: false

stages:
  # -------------------------
  # Stage 1 — Build (CI Build)
  # -------------------------
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build Frontend
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Use Node.js $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              set -eu
              npm install -g pnpm@$(PNPM_VERSION)
            displayName: Install pnpm $(PNPM_VERSION)

          - script: |
              set -eu
              pnpm config set store-dir $(PNPM_STORE_PATH)
            displayName: Configure pnpm store

          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(FRONTEND_APP_LOCATION)/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: $(PNPM_STORE_PATH)
              cacheHitVar: CACHE_RESTORED

          - script: |
              set -eu
              cd $(FRONTEND_APP_LOCATION)
              pnpm install --frozen-lockfile
              pnpm run lint
              # pnpm test
              pnpm run build
            displayName: Install dependencies and build

          # Publish build output
          - task: PublishPipelineArtifact@1
            displayName: Publish build output (dist) as artifact
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/dist
              artifact: frontend-dist
              publishLocation: pipeline

  # -------------------------
  # Stage 2 — Test (CI Quality Gate)
  # -------------------------
  - stage: Test
    displayName: Test
    dependsOn: Build
    jobs:
      - job: IntegrationTests
        displayName: Integration Testing
        steps:
          - script: |
              echo "TODO: integration testing"
              displayName: Placeholder
        #TODO
  # -------------------------
  # Stage 3 — Security (Shift-left Security)
  #   - SAST (Static Application Security Testing)
  #   - SCA (Software Composition Analysis -> dependency/vulnerability scanning)
  #   - Secrets scanning
  #   - SBOM generation
  # -------------------------
  - stage: Security
    displayName: Security Scans
    dependsOn: Test
    jobs:
      - job: Security
        displayName: Run Security Controls
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(PYTHON_VERSION)

          - task: NodeTool@0
            displayName: Use Node.js $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              set -eu
              npm install -g pnpm@$(PNPM_VERSION)
            displayName: Install pnpm $(PNPM_VERSION)

          - script: |
              set -eu
              pnpm config set store-dir $(PNPM_STORE_PATH)
            displayName: Configure pnpm store

          - task: Cache@2
            displayName: Restore pnpm store cache
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(FRONTEND_APP_LOCATION)/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: $(PNPM_STORE_PATH)
              cacheHitVar: CACHE_RESTORED

          - script: |
              set -eu
              cd $(FRONTEND_APP_LOCATION)
              pnpm install --frozen-lockfile
            displayName: Install dependencies

          # -------------------------
          # SAST — Semgrep
          # -------------------------
          - script: |
              set -eu
              pip install semgrep==$(SEMGREP_VERSION)
              cd $(FRONTEND_APP_LOCATION)
              semgrep --config=p/default --error --sarif --output semgrep.sarif
            displayName: SAST - Semgrep Scan

          - task: PublishPipelineArtifact@1
            displayName: Publish Semgrep SARIF
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/semgrep.sarif
              artifact: semgrep-sarif
              publishLocation: pipeline

          # -------------------------
          # Secrets Scanning — Gitleaks
          # -------------------------
          - script: |
              set -eu
              wget -q https://github.com/gitleaks/gitleaks/releases/download/v$(GITLEAKS_VERSION)/gitleaks_$(GITLEAKS_VERSION)_linux_x64.tar.gz
              tar -xzf gitleaks_$(GITLEAKS_VERSION)_linux_x64.tar.gz
              sudo mv gitleaks /usr/local/bin/gitleaks

              gitleaks dir \
                $(Build.SourcesDirectory)/$(FRONTEND_APP_LOCATION) \
                --report-format sarif \
                --report-path gitleaks.sarif \
                --redact \
                --exit-code 1

            displayName: Secrets Scan - Gitleaks

          - task: PublishPipelineArtifact@1
            displayName: Publish Gitleaks Report
            inputs:
              targetPath: gitleaks.sarif
              artifact: gitleaks-sarif

          # -------------------------
          # SBOM — CycloneDX (cdxgen)
          # -------------------------
          - script: |
              set -eu
              cd $(FRONTEND_APP_LOCATION)
              npm install -g @cyclonedx/cdxgen@$(CDXGEN_VERSION)
              cdxgen -o sbom.json
            displayName: Generate SBOM

          # Publish SBOM artifact
          - task: PublishPipelineArtifact@1
            displayName: Publish SBOM
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/sbom.json
              artifact: sbom
              publishLocation: pipeline

          # -------------------------
          # SCA — Trivy (Scan SBOM)
          # -------------------------

          # TODO: cache the db
            
          - script: |
              set -euo pipefail
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v$(TRIVY_VERSION)

              cd $(FRONTEND_APP_LOCATION)

              trivy fs \
              --severity HIGH,CRITICAL \
              --exit-code 1 \
              --scanners vuln \
              --format json \
              --output trivy-results.json .
            displayName: SCA - Trivy SBOM Scan

          # Publish Trivy SCA Report
          - task: PublishPipelineArtifact@1
            displayName: Publish Trivy SCA Report
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/trivy-sbom.json
              artifact: trivy-sca
              publishLocation: pipeline


  # -------------------------
  # Stage 4 — Deploy to Staging (CD Non-Prod)
  # -------------------------
  - stage: Deploy_Staging
    displayName: Deploy to Staging
    dependsOn: Security
    jobs:
      - deployment: FrontendStaging
        displayName: Frontend - Deploy to Kelix Staging
        environment: Kelix-Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: frontend-dist
                  displayName: Download frontend-dist artifact

                # Deploy the artifact without rebuilding (skip_app_build: true)
                # AzureStaticWebApp expects a folder path containing the built static assets.
                - task: AzureStaticWebApp@0
                  displayName: Deploy to Azure Static Web Apps (Staging)
                  inputs:
                    workingDirectory: '$(Pipeline.Workspace)'  # ← KEY: Set working directory
                    app_location: 'frontend-dist'
                    output_location: ''
                    skip_app_build: true
                    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN_STATIC_STAGING)