# frontend-staging.yml
# Kelix Frontend — Staging CI/CD (PR validation + staging deploy)
#
# Behavior:
# - PR to staging: Build + Test + Security
# - Push to staging: Build + Test + Security + Deploy to Staging

trigger:
  branches:
    include:
      - staging

pr:
  branches:
    include:
      - staging

pool:
  vmImage: ubuntu-24.04

variables:
  NODE_VERSION: '24.13.0'
  PNPM_VERSION: '10.15.1'
  TRIVY_VERSION: '0.68.2'
  SEMGREP_VERSION: '1.148.0'
  GITLEAKS_VERSION: '8.30.0'
  CDXGEN_VERSION: '12.0.0'
  PYTHON_VERSION: '3.12'
  FRONTEND_APP_LOCATION: 'app'
  PNPM_STORE_PATH: $(Pipeline.Workspace)/.pnpm-store
  CACHE_RESTORED: false

stages:
  # -------------------------
  # Stage 1 — Build (CI Build)
  # -------------------------
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build Frontend
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Use Node.js $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: npm install -g pnpm@$(PNPM_VERSION)
            displayName: Install pnpm $(PNPM_VERSION)

          - script: |
              pnpm config set store-dir $(PNPM_STORE_PATH)
            displayName: Configure pnpm store

          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(FRONTEND_APP_LOCATION)/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: $(PNPM_STORE_PATH)
              cacheHitVar: CACHE_RESTORED

          - script: |
              cd $(FRONTEND_APP_LOCATION)
              pnpm install --frozen-lockfile
              pnpm run build
            displayName: Install dependencies and build

          # Publish build output
          - task: PublishPipelineArtifact@1
            displayName: Publish build output (dist) as artifact
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/dist
              artifact: frontend-dist
              publishLocation: pipeline



  # -------------------------
  # Stage 2 — Test (CI Quality Gate)
  # -------------------------
  - stage: Test
    displayName: Test
    dependsOn: Build
    jobs:

      # -------------------------
      #  Lint and Unit Tests
      # -------------------------
      - job: UnitAndLint
        displayName: Lint and Unit Tests
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: Use Node.js $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)

          # Install pnpm
          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm --version
            displayName: Install pnpm $(PNPM_VERSION)

          # Configure pnpm store
          - script: |
              pnpm config set store-dir $(PNPM_STORE_PATH)
              pnpm config get store-dir
            displayName: Configure pnpm store

          # Restore pnpm cache
          - task: Cache@2
            displayName: Restore pnpm store cache
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(FRONTEND_APP_LOCATION)/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: $(PNPM_STORE_PATH)
              cacheHitVar: CACHE_RESTORED

          # Install dependencies
          - script: |
              cd $(FRONTEND_APP_LOCATION)
              pnpm install --frozen-lockfile
            displayName: Install dependencies

          # lint + unit tests
          - script: |
              cd $(FRONTEND_APP_LOCATION)
              pnpm run lint -- --max-warnings=0
              # pnpm test -- --ci
            displayName: Run lint and unit tests

  # -------------------------
  # Stage 3 — Security (Shift-left Security)
  #   - SAST (Static Application Security Testing)
  #   - SCA (Software Composition Analysis -> dependency/vulnerability scanning)
  #   - Secrets scanning
  #   - SBOM generation
  # -------------------------
 
  - stage: Security
    displayName: Security Scans
    dependsOn: Test
    jobs:
      - job: Security
        displayName: Run Security Controls
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(PYTHON_VERSION)

          - task: NodeTool@0
            displayName: Use Node.js $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: npm install -g pnpm@$(PNPM_VERSION)
            displayName: Install pnpm $(PNPM_VERSION)

          - script: |
              pnpm config set store-dir $(PNPM_STORE_PATH)
            displayName: Configure pnpm store

          - task: Cache@2
            displayName: Restore pnpm store cache
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(FRONTEND_APP_LOCATION)/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: $(PNPM_STORE_PATH)
              cacheHitVar: CACHE_RESTORED

          - script: |
              cd $(FRONTEND_APP_LOCATION)
              pnpm install --frozen-lockfile
            displayName: Install dependencies

          # -------------------------
          # SAST — Semgrep
          # -------------------------
          - script: |
              pip install semgrep==$(SEMGREP_VERSION)
              cd $(FRONTEND_APP_LOCATION)
              semgrep scan --config p/ci --severity ERROR --exit-code 1 --sarif --output semgrep.sarif
            displayName: SAST - Semgrep Scan

          - task: PublishPipelineArtifact@1
            displayName: Publish Semgrep SARIF
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/semgrep.sarif
              artifact: semgrep-sarif
              publishLocation: pipeline

          # -------------------------
          # Secrets Scanning — Gitleaks
          # -------------------------
          - script: |
              wget -q https://github.com/gitleaks/gitleaks/releases/download/v$(GITLEAKS_VERSION)/gitleaks_$(GITLEAKS_VERSION)_linux_x64.tar.gz
              tar -xzf gitleaks_$(GITLEAKS_VERSION)_linux_x64.tar.gz
              sudo mv gitleaks /usr/local/bin/gitleaks

              gitleaks detect \
              --source $(Build.SourcesDirectory)/$(FRONTEND_APP_LOCATION) \
              --report-format json \
              --report-path gitleaks-report.json \
              --redact \
              --exit-code 1
            displayName: Secrets Scan - Gitleaks

          - task: PublishPipelineArtifact@1
            displayName: Publish Gitleaks Report
            inputs:
              targetPath: gitleaks-report.json
              artifact: gitleaks-report

          # -------------------------
          # SBOM — CycloneDX (cdxgen)
          # -------------------------
          - script: |
              cd $(FRONTEND_APP_LOCATION)
              npm install -g @cyclonedx/cdxgen@$(CDXGEN_VERSION)
              cdxgen -o sbom.json
            displayName: Generate SBOM

          # -------------------------
          # SCA — Trivy (Scan SBOM)
          # -------------------------
          - script: |
              wget -q https://github.com/aquasecurity/trivy/releases/download/v$(TRIVY_VERSION)/trivy_$(TRIVY_VERSION)_Linux-64bit.tar.gz
              tar -xzf trivy_$(TRIVY_VERSION)_Linux-64bit.tar.gz
              sudo mv trivy /usr/local/bin/trivy
              sudo chmod +x /usr/local/bin/trivy

              cd $(FRONTEND_APP_LOCATION)

              trivy sbom \
                --severity HIGH,CRITICAL \
                --exit-code 1 \
                --format json \
                --output trivy-sbom.json \
                sbom.json
            displayName: SCA - Trivy SBOM Scan

          # Publish SBOM artifact
          - task: PublishPipelineArtifact@1
            displayName: Publish SBOM
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/sbom.json
              artifact: sbom
              publishLocation: pipeline

          # Publish Trivy SCA Report
          - task: PublishPipelineArtifact@1
            displayName: Publish Trivy SCA Report
            inputs:
              targetPath: $(FRONTEND_APP_LOCATION)/trivy-sbom.json
              artifact: trivy-sca
              publishLocation: pipeline


  # -------------------------
  # Stage 4 — Deploy to Staging (CD Non-Prod)
  # -------------------------

  - stage: Deploy_Staging
    displayName: Deploy to Staging
    dependsOn: Security
    condition: and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/staging'),
          eq(variables['Build.Reason'], 'Manual')
        )
      )
    jobs:
      - deployment: FrontendStaging
        displayName: Frontend - Deploy to Kelix Staging
        environment: Kelix-Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: frontend-dist
                  displayName: Download frontend-dist artifact

                # Deploy the artifact without rebuilding (skip_app_build: true)
                # AzureStaticWebApp expects a folder path containing the built static assets.
                - task: AzureStaticWebApp@0
                  displayName: Deploy to Azure Static Web Apps (Staging)
                  inputs:
                    workingDirectory: '$(Pipeline.Workspace)'  # ← KEY: Set working directory
                    app_location: 'frontend-dist'
                    output_location: ''
                    skip_app_build: true
                    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN_STATIC_STAGING)